apiVersion: v1
kind: Namespace
metadata:
  name: dgs-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azuregamingcontroller-sa
  namespace: dgs-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: azuregamingcontroller-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: azuregamingcontroller-sa
    # Reference to upper's `metadata.namespace`
    namespace: dgs-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-gaming-apiserver
  namespace: dgs-system
  labels:
    name: aks-gaming-apiserver
spec:
  selector:
    matchLabels: 
      name: aks-gaming-apiserver
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        name: aks-gaming-apiserver
    spec:
      serviceAccountName: azuregamingcontroller-sa
      containers:
      - name: aks-gaming-apiserver
        image: docker.io/dgkanatsios/aks_gaming_apiserver:0.0.47
        args: ["./apiserver","--port","8000"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 50m
            memory: 30Mi
          requests:
            cpu: 50m
            memory: 20Mi
        ports:
        - containerPort: 8000
          protocol: TCP
        volumeMounts:
        - name: certificate
          mountPath: "/certificate"
          readOnly: true
      volumes:
      - name: certificate
        secret:
          secretName: aks-gaming-certificate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-gaming-controller
  namespace: dgs-system
  labels:
    name: aks-gaming-controller
spec:
  selector:
    matchLabels: 
      name: aks-gaming-controller
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        name: aks-gaming-controller
    spec:
      serviceAccountName: azuregamingcontroller-sa
      containers:
      - name: aks-gaming-controller
        args: ["./controller","--podautoscaler","true"]
        image: docker.io/dgkanatsios/aks_gaming_controller:0.0.47
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 50m
            memory: 30Mi
          requests:
            cpu: 50m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: aks-gaming-apiserver
  namespace: dgs-system
  labels:
    name: aks-gaming-apiserver
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: aks-gaming-apiserver
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: aks-gaming-webhookserver
  namespace: dgs-system
  labels:
    name: aks-gaming-webhookserver
spec:
  ports:
    # the port that this service should serve on
    - port: 443
      targetPort: 8001
      protocol: TCP
      name: https
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: aks-gaming-apiserver
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: aks-gaming-certificate
  namespace: dgs-system
type: Opaque
data:
  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVjekNDQWx1Z0F3SUJBZ0lRS0g1dmxsaGJtQnI1b05sN05VaWgzVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TURFd01Ea3hPRE16TWpaYUZ3MHlNVEV3TURreE9ETXpNalphTURJeApNREF1QmdOVkJBTVRKMkZyY3kxbllXMXBibWN0ZDJWaWFHOXZhM05sY25abGNpNWtaM010YzNsemRHVnRMbk4yCll6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtmeXZaZUUxblNsVEI4WndKU28Kb2JHelFMdUdGZ3NxYTcwQW1YaS9QNnIvZ3R2WDl5SDRJS0ZHQUZpWDY0cS9EQUN2UFc2cEZOcWFnMys5c09INQozZTVsd1NzREI5RUJ4U3NqYjdjemF5V0YwRXJXWk52MDF0UU1HRmtUSHZ6Z3R5amdZN2JyMUhKWnBmcThzRzdtCit4RlJycHZCRVpRYWt1V3B2VEN2Qnhvb2NEYWtnUzhQRGEvdGRlS2VzM2VLbnZEdUk5dVk4R1JRVEh2QUxSaXYKTmozS2RnWTRLT0JFaENyYldDZmxsSlkrUWRvU0FvUHNEQkpBTlN4UEVQTDE4S1RwTm95ZTJoS3VOK0lTZjBMVQp6Yng0QzQ1WUdPQlltM0pGQ0JtMXJyZTVnNFo3NXErQXlvYmVHSHpmem1HMWxuN1F1WWNxU3RsTFZhbTdBOFlDCmlYRUNBd0VBQWFPQnFUQ0JwakFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdFd0RBWURWUjBUQVFIL0JBSXdBREJ4QmdOVkhSRUVhakJvZ2hoaGEzTXRaMkZ0YVc1bkxYZGxZbWh2YjJ0egpaWEoyWlhLQ0kyRnJjeTFuWVcxcGJtY3RkMlZpYUc5dmEzTmxjblpsY2k1a1ozTXRjM2x6ZEdWdGdpZGhhM010CloyRnRhVzVuTFhkbFltaHZiMnR6WlhKMlpYSXVaR2R6TFhONWMzUmxiUzV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUwKQlFBRGdnSUJBSWNhd3NiSWprVVh2dDJkMjUvdHpnVlNrallJSjFsQ05WeFBZSTBaWDNLMk9zdGlHcHpMNmM2cwpDRWMwQW8vbUZ6a0c0Z2x3T1BmVW80Rk1oVm41ekdFUXQ5OS9CYkF3blFiMUZGTklMQ3BxUXRuZE5SVnBHbEJvClVUM2djQi91MW1MN0RyRjlxRGpPTmd3RTVubU1SbXdhenNKb0hRbCtTZS90SXJIMG9LYmZEaVI1cFU2TWNOb1cKTW5SZkFvZFpSa29NcWQ2c0J0OTFnMjNjR3ljSjhOMk5mR2VJRUxmNm16cENsQ2lhdzB2aVVaU2poNmxURFNKVwpNbWNua3RIdmppWkk2UEhJQnZDSGdocmtTekVxVlRUcHhyWWNhUzlITG9EbHVFS2NoNS9oUmIwZHNnVC95emVsCnlHRzJDcGQ4dlhvMXMzbHhUcDFqdUY5MkwwS2tUMVkxY2ErWUVldlRiZkpFVGM4QzFJRTVRb3ZqdWtSSE9JaUUKSlpjeDBJWmFFR3VoN2FGU0F4Z1UyZlp4VFRDTTR1OHROK0w3TkhNaEI5ek5uT25wMERiaG94Vi9zV1NZM2RsVgpLWlc2S21vWHJzWE9mZXh1dThVUHhVVmlqRkVnTXBWTjFoSTkzN0MzcFRyMkJ0a3Vpb0pid0pRcHBXeU9jNVZBCjhBSDdPMFBGN0toV3pQaVBTcU9zUUhYb3FXRHVWVHp5ZkhuR1dFbStpTzkyRWlXdS9uMUpJVjlncUVyRnU3K1MKZjd3UjdnTWQwV0pnWHNVNjNKblgyMXhOdmYrMEQ5bGhIQ2JYajVTbmJaOWJuSHQrRlMreWw5TzRrQUd6eXUxTQp4NnZCWjByVFBsS1RkVDlzTHNaYm5mbEJOMllIeEVSYTBPODVWQkpIc1U2eUxPUG85UkRICi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcC9LOWw0VFdkS1ZNSHhuQWxLaWhzYk5BdTRZV0N5cHJ2UUNaZUw4L3F2K0MyOWYzCklmZ2dvVVlBV0pmcmlyOE1BSzg5YnFrVTJwcURmNzJ3NGZuZDdtWEJLd01IMFFIRkt5TnZ0ek5ySllYUVN0WmsKMi9UVzFBd1lXUk1lL09DM0tPQmp0dXZVY2xtbCtyeXdidWI3RVZHdW04RVJsQnFTNWFtOU1LOEhHaWh3TnFTQgpMdzhOcisxMTRwNnpkNHFlOE80ajI1andaRkJNZThBdEdLODJQY3AyQmpnbzRFU0VLdHRZSitXVWxqNUIyaElDCmcrd01Fa0ExTEU4UTh2WHdwT2syako3YUVxNDM0aEovUXRUTnZIZ0xqbGdZNEZpYmNrVUlHYld1dDdtRGhudm0KcjRES2h0NFlmTi9PWWJXV2Z0QzVoeXBLMlV0VnFic0R4Z0tKY1FJREFRQUJBb0lCQUdibDRXVW8vUi9nZXAvLwpiaTltbGhMQ3lhRmJDTHgwbENmcmF4eEF5S2hpL2ZEbUE4TXJQQXF6VWRqMTAxbGhyZC9wZmhFRHhRUWVjUHpkCjRyYkJHVWxMektzbW95NWFFRXhhM01KNDNXZlM4WWc0alBqNnJIaWtwSEpHdGRDbmVYQ3c4a2NMZkZGSFBkcysKcWpaNGpGRFRJOURIM0paS0pjQlNXOWl0RkFQZ3pySXllT2RwSWlHY0JvRENqWlZyMVUyaHFsMy9WNk50RktWcApsdEJNMUtyaHNheTN3c1gwQWhCK2pKZmpXY2Zady95a21aMG9XL25uMmZsU2xUelBETTBTOTZQSFJpYlFuZldlCklPdjVQNzBiOUJMWjNwZnp3VmdtaGVGS2ZORVhadDRLZ2lKQmk5R1A3cS9TSG4xS21BbXhFam42VmtxbU8rcWYKSEtLWEEwVUNnWUVBejhwc0k3ZktXSGtoUlhqOEJOLzg5WDdqNldMaGJldTFmdzFvRUFWY1RxYkJoSlRWUW5DbQpGWlVUcHc4cFdncXpBRFQ2aXBSL213QTJZYkl6Y1ZmUXoxbjJNTGVPRzZwYWFlRVVhY1VoR2JDMWxib1duWkJ1CjhNSkJjMWNYSUNpczJVTmNxTEZPWis2cGk5WU9nZkhQVEZSakhWanRpM01laFZGTUZ4eTF6djhDZ1lFQXp1bm0KelIzSzlLalB6QWVzZjQyS2ZyYVFzKzNibXJUUHVEZGFZQjlFZzkxTi9NdVY4bERMVDA4NjM0QitDd2EveklRUgprY1ZSdUh0bGdIV0I3ZXBLUWZyUTBjYnJJTXVoQnc3SVM3dnRSdVNscmZsWmRzTFgvZDFKdnBrakpMaE1YVFhJCktCTTV3dURkQkZ5WnJQNC9Vck5ybHV1Z3J3VXZsV2tDZklRbEY0OENnWUVBc0Q4ZDRsM3QvNFVldDNLYk1QZGIKOUU4Z3VjRHBQUGNGQnpNejVRTG0vTDlzdlN3UWh6NU5ZVmtGUmxvUjFSSG1LbkxGWCszOUhsZmJ5Sm9DRUUxUQpDOUJlaFl2cnVZT1JGT1daRHUzcDJZU05RT2FLY0RNbUpvaGVRNXJIUHJ2QmdMY21UTiszaFdobDN2bzlhL0xTCnhnZDkybEtuaWZTbkdxV09TTHhOYWJrQ2dZRUFxSzRRWlBrN3duWjRhSmw4NjhORXU0WXpzeXRla3VHQ1VXaDIKdWRQanRDaE84cDQ1a0lDRExoV21KaHlISkpBTS9qcFFaR2phOVMxTGt3eTRybThJdUg4emkwREI0RXVBNjlNRwpRSTlrb1IyM1gzdmVqaTNMalg3QUpxeUs5TjEyQzZyVGtMQVRyNlpISjg0aHplQzdXTDFDSVpmWHQ3YmZrc3MzCnByREgyRXNDZ1lCalBLdWR5Y25YU1pBTENpTUNkRkdiQXZ5ZVFZZWNZL2Naak1DZ3FLZ1pLTHdKNU5oT3E4Mk8KdEFiN0d0MVVLSFVQOXRBbHp3ZFNRMHlHOGQ5YWVZaDRwYXVZdTVVQ3c4S1NiSWlMeDZJaHh2T3c5T1E5MU5xOApIZ0JXYUc2VzNqVnNaZmYvU3ZXalZaQ2lxSTVlSDgwRkZQUG52N0ZUeHBjRDFpV05VdEYzMGc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: aks-gaming-webhook-mutation
  namespace: dgs-system
webhooks:
  - name: aks-gaming-webhookserver-mutation.azuregaming.com
    clientConfig:
      service:
        name: aks-gaming-webhookserver
        namespace: dgs-system
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV5VENDQXJHZ0F3SUJBZ0lRQXptYXV5b0NScDV4eGJHQUVRenAzVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWdGdzB5TURFd01Ea3dNREV6TkRoYUdBOHlNRFV3TVRBd09UQXdNak0wT0ZvdwpEVEVMTUFrR0ExVUVBeE1DWTJFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUN5CmxIc0pvNzNFM3VCdlB6dGNHb010WkRUUUNtV2R4czc2NlZuWTZFYWthK3RpWVZuekJPeml0UkxwS1BnT1VwZEYKSHlMK1h0Tzlud081UHNrOUJxMzl6VjRJRFFiMVczNS9ERXNoYXVocmN3ek5OYktoZHg5SkVMTjhiUU45RWJsNApTcUZVbzBDeEoyalZnRHZkYVBxeWU2RHQrNWx2Z2RvU2l6Vk1BL0RYNjZrejRSRzEvOWNmOXhycERWZ2xUN29iCkpvUmR3dGdHWWR4Y2M4d0hSNUovUXlsTDdsbURLR0RjSUlwNkdOcjNqUFY0QTZPY3gza0JjQmdLeDJnN3UyL3kKRjNkVTZUTlYycXdmcGhqSU8rYjA5OEZ4czMvbFovTm5HL0lzeGorWjFTS2xqQkk5YnhyYVg5QVhEVWlYMTRvcwoxTXlpMXYxV2tTTnl5cEl4emNMVU5MY1BJTmJUNHdSd25pOHFUUW5RZCt4ZjB3VlZHdHJ1S2ZqaHNCUm9GKzUxCmxVSi96WG9WV05JK0oybmw5cmdLaEJlejVSNE5Ed3ZvOHRMK05HTDQyQ3I0cHFEdlJxdlNpaXlNdFBLTHkxTWUKYUs4QjBENWV2ZkRQMGJWUHFpeEJqUnVISWpKNnpaa1gxNE5KcW92UTcySHV4bDFjcE0rQk9PNE1JNTJtQ1JMbApkb0s5U3BXV2t0VStOR1dOL0hHMEdvcFQ0RXZUSW9XU3YrWk1HV1hTaEFxVXJYcGNaaW9KZlZYeGEvbHB4S2pyClhSWmRoNTJuZ0Vvem9RbktObE5YQmFrZnVCYzF0MG9PcTBqVWtJM1Nmd1NvVnI3THBSbGVtYURVWHp3OS90VzMKN0l0RFNFUG9WTTN4bVVDVHdpNlVnMXZ2Q2V0cnJoM2ZEQ3RnbE9JdFFRSURBUUFCb3lNd0lUQU9CZ05WSFE4QgpBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFYTnVCCmVVWk9pQTU3RE9NQlkvMW53UEZscExuS3EyQmgraTkxcEh0aVlib3BwWGVkenJZVXZNVkpFVTA0WFhGSUgzRSsKamNCc3dIUzFBcm9wWnZKTEFKQVR5Kzd6OGRiSngraWJFRlAzR2UvL3F2YnpVSTF3ZXVhcGc2WXBGOVFPQ1gxWgpYU2VoMkVKSys3aDlpZXJ0STFlYnJRckRFbzY1NWErOHdPdHFpMXR3ODlRWEFZNDFXeWpISXFRZDArVGFjdkhtCkpYQXdMTll1b1IwOERHaHVuTmVTcUx2a3k4RzBDN2p0NWFDTVRwVUFzTFhGcTZrSXFUSjlldlZKT29YL1l1MFEKZ1V2ZDA2WktTenhIWG1mNjZiaFhzYXdhem1XQjZlYTNxSGhHU0pGejgwV1IzWFV1K2VKMDgvL3ZZWWxEeDhuUgpXQXhuWldBZlJYY3E1cmUyUHhBY2wrOUVQeThIeE12cXdDQlFyZFJBeGprTGNoUGR5cGFDOFJjbTFwbkRTc1I5CmZpOCthL0FGbzA0ZlRXRlNndU5WRWZLOEk5QWpnRHdZMXhtdmd1U3ZSSXJLK0NYblkyN0U0ZFR3TG5aYVFkWHIKamNtTVhHdkNoeW5KbkJlTUpvZ05jUlg3UkFyU1k3OHpzOG5MdkdkK3hCbnltMEs0Ri8zaGgyQ283RUpCM1UvMApUeU9zVVYreURrb3lxQmRLSFdERmNDWldLWE8yTTBSV3MzR0RnOWxHMFVpMlVrRmRHVUJlY2ZYcFdTNzg4SE1KCkljaGZQRDNiNHRKbHRuTGJ0TVZyU1hJR0dQaWhBMk5IaWpGL3FUbFB5MjI1QmNrSnlOY2w2MHZoTmhzYTYveU8KS0dGbFU4ZURTOVJIK2Fmb1MrUEozQ0pBaksvRnVBQ0lVYkdLY2Q4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["azuregaming.com"]
        apiVersions: ["v1alpha1"]
        resources: ["dedicatedgameservercollections","dedicatedgameservers"]
    failurePolicy: Fail
